add metadata yaml generation
signalfx/splunk-otel-js pull request #866
Opened 2024-01-10 11:36 UTC by seemk

If possible the instrumentation target library versions are taken from dependency READMEs (however in the future a better mechanism is needed to gather these automatically, something to discuss in the JS sig).

2024-01-10 11:57 UTC, theletterf requested changes
Great! There are a few things that need addressing:

- There seem to be a lack of indentation for certain items. For example, items inside each first level object are not indented. Not sure if this would pose a problem to YAML parsers, but I'd much rather have indentation for readability and browsing purposes. 
The same indentation issues appears in nested items, such as the dependencies within the resource detectors.

- There is no first level `instrumentations:` object — keys start right after the settings.

- No resource attribute information nor dependencies info, but I think it's OK for the latter to just resort to npm, especially if there are MANY dependencies. WDYT?

- To preserve the same structure used by .NET, please rename the name key in settings to env.

With this, I think we'd already have an useful artifact for testing.

2024-01-17 10:34 UTC, seemk commented
> Great! There are a few things that need addressing:
> 
> * There seem to be a lack of indentation for certain items. For example, items inside each first level object are not indented. Not sure if this would pose a problem to YAML parsers, but I'd much rather have indentation for readability and browsing purposes.
>   The same indentation issues appears in nested items, such as the dependencies within the resource detectors.

Should have better indenting now and verified it's parseable.

> * There is no first level `instrumentations:` object — keys start right after the settings.

Fixed

> * No resource attribute information nor dependencies info, but I think it's OK for the latter to just resort to npm, especially if there are MANY dependencies. WDYT?

Added resource detectors, I can add the dependency list for sure, but is there an actual need for it? Should they be first level dependencies?

> * To preserve the same structure used by .NET, please rename the name key in settings to env.
> 

Done!

2024-01-17 11:48 UTC, theletterf commented
@seemk Could we try with adding them as first-level deps and see what comes out? If it's not too much work, that is.

2024-01-19 12:26 UTC, seemk commented
> @seemk Could we try with adding them as first-level deps and see what comes out? If it's not too much work, that is.

Added first level dependencies, the output is now

```
component: Splunk Distribution of OpenTelemetry JavaScript
version: 2.6.1
settings:
- env: OTEL_ATTRIBUTE_VALUE_LENGTH_LIMIT
  description: Maximum allowed attribute value size
  default: 12000
  type: number
  category: instrumentation
- env: OTEL_BSP_SCHEDULE_DELAY
  description: The delay in milliseconds between 2 consecutive bath span processor exports.
  default: 500
  type: number
  category: instrumentation
- env: OTEL_EXPORTER_OTLP_CERTIFICATE
  description: Path to a certificate to use when verifying a server's TLS credentials.
  default: 
  type: string
  category: exporter
- env: OTEL_EXPORTER_OTLP_CLIENT_CERTIFICATE
  description: Path to a certificate to use when verifying a client's TLS credentials.
  default: 
  type: string
  category: exporter
- env: OTEL_EXPORTER_OTLP_CLIENT_KEY
  description: Path to client's private key to use in mTLS communication in PEM format.
  default: 
  type: string
  category: exporter
- env: OTEL_EXPORTER_OTLP_ENDPOINT
  description: The OTLP endpoint to export to.
  default: http://localhost:4317
  type: string
  category: exporter
- env: OTEL_EXPORTER_OTLP_TRACES_PROTOCOL
  description: Chooses the trace exporter protocol. Allowed values are grpc and http/protobuf
  default: grpc
  type: string
  category: exporter
- env: OTEL_EXPORTER_OTLP_METRICS_PROTOCOL
  description: Chooses the metric exporter protocol. Allowed values are grpc and http/protobuf
  default: grpc
  type: string
  category: exporter
- env: OTEL_EXPORTER_OTLP_PROTOCOL
  description: The protocol to use for OTLP exports.
  default: grpc
  type: string
  category: exporter
- env: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
  description: The traces OTLP endpoint to export to.
  default: http://localhost:4317
  type: string
  category: exporter
- env: OTEL_INSTRUMENTATION_COMMON_DEFAULT_ENABLED
  description: Whether to activate all the embedded instrumentations. When you set this setting to false, use OTEL_INSTRUMENTATION_<NAME>_ENABLED=true to selectively turn on instrumentations.
  default: true
  type: boolean
  category: instrumentation
- env: OTEL_LOG_LEVEL
  description: Log level for the OpenTelemetry diagnostic console logger. To activate debug logging, set the debug value. Available values are error, info, debug, and verbose.
  default: none
  type: string
  category: general
- env: OTEL_METRIC_EXPORT_INTERVAL
  description: The interval, in milliseconds, of metrics collection and exporting.
  default: 30000
  type: number
  category: exporter
- env: OTEL_METRICS_EXPORTER
  description: Comma-separated list of metrics exporter to use. To output to the console, set the variable to console. If set to none, metric exports are turned off.
  default: otlp
  type: string
  category: exporter
- env: OTEL_PROPAGATORS
  description: Comma-separated list of propagators you want to use.
  default: tracecontext,baggage
  type: string
  category: general
- env: OTEL_SERVICE_NAME
  description: Name of the service or application you’re instrumenting. Takes precedence over the service name defined in the OTEL_RESOURCE_ATTRIBUTES variable.
  default: unnamed-node-service
  type: string
  category: general
- env: OTEL_SPAN_LINK_COUNT_LIMIT
  description: Maximum number of links per span.
  default: 1000
  type: number
  category: general
- env: OTEL_TRACES_EXPORTER
  description: Comma-separated list of trace exporters to use. To output to the console, set the variable to console.
  default: otlp
  type: string
  category: exporter
- env: SPLUNK_ACCESS_TOKEN
  description: A Splunk authentication token that lets exporters send data directly to Splunk Observability Cloud. Required if you need to send data to the Splunk Observability Cloud ingest endpoint.
  default: 
  type: string
  category: general
- env: SPLUNK_INSTRUMENTATION_METRICS_ENABLED
  description: Emit metrics from instrumentation (e.g. http.server.duration)
  default: false
  type: boolean
  category: instrumentation
- env: SPLUNK_METRICS_ENABLED
  description: Activates metrics collection.
  default: false
  type: boolean
  category: general
- env: SPLUNK_METRICS_ENDPOINT
  description: The metrics endpoint. Takes precedence over OTEL_EXPORTER_OTLP_METRICS_ENDPOINT. When SPLUNK_REALM is used, the default value is https://ingest.<realm>.signalfx.com/v2/datapoint/otlp.
  default: 
  type: string
  category: general
- env: SPLUNK_PROFILER_CALL_STACK_INTERVAL
  description: Frequency with which call stacks are sampled, in milliseconds.
  default: 1000
  type: number
  category: profiler
- env: SPLUNK_PROFILER_ENABLED
  description: Activates AlwaysOn CPU profiling.
  default: false
  type: boolean
  category: profiler
- env: SPLUNK_PROFILER_LOGS_ENDPOINT
  description: The collector endpoint for profiler logs.
  default: http://localhost:4317
  type: string
  category: profiler
- env: SPLUNK_PROFILER_MEMORY_ENABLED
  description: Activates memory profiling for AlwaysOn Profiling.
  default: false
  type: string
  category: profiler
- env: SPLUNK_REALM
  description: The name of your organization’s realm, for example, us0. When you set the realm, telemetry is sent directly to the ingest endpoint of Splunk Observability Cloud, bypassing the Splunk Distribution of OpenTelemetry Collector.
  default: 
  type: string
  category: general
- env: SPLUNK_REDIS_INCLUDE_COMMAND_ARGS
  description: Whether to include the full Redis query in db.statement span attributes when using the Redis instrumentation.
  default: false
  type: boolean
  category: instrumentation
- env: SPLUNK_RUNTIME_METRICS_COLLECTION_INTERVAL
  description: The interval, in milliseconds, during which GC and event loop statistics are collected.
  default: 5000
  type: number
  category: instrumentation
- env: SPLUNK_RUNTIME_METRICS_ENABLED
  description: Activates the collection and export of runtime metrics. Runtime metrics are only sent if the SPLUNK_METRICS_ENABLED environment variable is set to true or if memory profiling is activated.
  default: true
  type: boolean
  category: instrumentation
- env: SPLUNK_TRACE_RESPONSE_HEADER_ENABLED
  description: Activates the addition of server trace information to HTTP response headers.
  default: true
  type: boolean
  category: general
- env: SPLUNK_TRACING_ENABLED
  description: Enables tracing.
  default: true
  type: boolean
  category: instrumentation
instrumentations:
  - keys:
    - "@opentelemetry/instrumentation-amqplib"
    instrumented_components:
      - name: "amqplib"
        supported_versions: ">=0.5.5"
    support: community
  - keys:
    - "@opentelemetry/instrumentation-aws-sdk"
    instrumented_components:
      - name: "aws-sdk and @aws-sdk"
        supported_versions: "2.x,3.x"
    support: community
  - keys:
    - "@opentelemetry/instrumentation-bunyan"
    instrumented_components:
      - name: "bunyan"
        supported_versions: "bunyan@^1.0.0"
    support: community
  - keys:
    - "@opentelemetry/instrumentation-cassandra-driver"
    instrumented_components:
      - name: "cassandra-driver"
        supported_versions: ">=4.4 <5.0"
    support: community
  - keys:
    - "@opentelemetry/instrumentation-connect"
    instrumented_components:
      - name: "connect"
        supported_versions: "^3.0.0"
    support: community
  - keys:
    - "@opentelemetry/instrumentation-dataloader"
    instrumented_components:
      - name: "dataloader"
        supported_versions: "^2.0.0"
    support: community
  - keys:
    - "@opentelemetry/instrumentation-dns"
    instrumented_components:
      - name: "dns"
        supported_versions: "*"
    support: community
  - keys:
    - "@opentelemetry/instrumentation-express"
    instrumented_components:
      - name: "express"
        supported_versions: "^4.0.0"
    support: community
  - keys:
    - "@opentelemetry/instrumentation-fastify"
    instrumented [...]

2024-01-19 15:03 UTC, theletterf commented
Seems reasonable! Let's go with it.

2024-01-19 19:19 UTC, mhennoch approved these changes

2024-01-19 19:20 UTC, seemk commented
> Seems reasonable! Let's go with it.

@theletterf You need to approve as well in this case

2024-01-22 09:40 UTC, merged